app:
    resource: '@AppBundle/Controller/'
    type: annotation

#core:
#    resource: '@CoreBundle/Controller/'
#    type: annotation

core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /core

platform:
    resource: "@OCPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform